ethereum/beacon-APIs

apis/validator/beacon-node-oapi.yaml

@djrtwo It seems that I've never committed and pushed to update #5, sorry

Validator details fixes

---

.circleci/config.yml
apis/validator/aggregate_and_proof.yaml
beacon-node-oapi.yaml
types/validator.yaml

Overlooked that in 0.11 spec validator needs to submit SignedAggregateAndProof

Fix invalid payload for aggregate and proof

---

.github/workflows/main.yml
apis/beacon/fork.yaml
apis/validator/beacon_committee_subscriptions.yaml
apis/validator/duties.yaml
types/primitive.yaml

resolves #38 
@djrtwo Can you protect master that it requires PR ci to pass?

Update swagger-cli action

---

.spectral.yml
apis/beacon/fork.yaml
apis/beacon/genesis.yaml
apis/node/syncing.yaml
apis/node/version.yaml
apis/validator/aggregate_and_proof.yaml
apis/validator/attestation.yaml
apis/validator/beacon_committee_subscriptions.yaml
apis/validator/block.yaml
apis/validator/duties.yaml
apis/validator/validators.yaml
beacon-node-oapi.yaml

I've added some more rules to have some standard in api definitions.
There are more rule examples here:
https://github.com/adidas/api-guidelines/blob/master/.spectral.yml
We can also add our own where we see fit.

Fix lint warnings

---

apis/node/identity.yaml
apis/node/peer.yaml
apis/node/syncing.yaml
apis/node/version.yaml

I thought conclusion was to have data envelop only on array responses but seems like there is majority to have "data" envelop on every endpoint to allow passing various metadata.

Add data envelop to node endpoints

---

apis/beacon/states/validator.yaml
apis/beacon/states/validators.yaml

ref: https://github.com/ethereum/eth2.0-APIs/issues/37#issuecomment-646583902

Clarify validator id

---

apis/validator/duties/proposer.yaml

Super minor fixes, see changes.

Minor typo fixes

---

apis/validator/sync_committee_contribution_and_proof.yaml
beacon-node-oapi.yaml
types/altair/sync_committee.yaml

basically add https://hackmd.io/@QYHAVYiHRg65pdI_CEm7Eg/syncommitteeapi#POST-ethv1validatorcontribution_and_proofs to standard api spec

POST `/eth/v1/validator/contribution_and_proofs`

---

apis/beacon/pool/sync_committees.yaml
beacon-node-oapi.yaml
types/altair/sync_committee.yaml

added based on https://hackmd.io/@QYHAVYiHRg65pdI_CEm7Eg/syncommitteeapi#POST-ethv1beaconpoolsync_committees

add POST `/eth/v1/beacon/pool/sync_committees`

---

apis/beacon/blocks/block.yaml
apis/debug/state.yaml
apis/validator/block.yaml

Mark old endpoints as deprecated

---

README.md

I think this is an important piece of info for those new to Swagger.

Add hint about "dev"

---

index.html

Fixed API Definition dropdown list to include API v2.2.0

API Definition dropdown list missed API v2.2.0

---

types/bellatrix/execution_payload.yaml

Should read `ExecutionPayloadHeader` not `ExecutionPayload`.

Use proper description for execution payload header

---

.redocly.yml

Fixes redocly config with latest version

chore: update redocly config

---

index.html

fix: allow query config override

---

.github/workflows/main.yml

chore: pin redocli version

---

CHANGES.md

Having a look at if we can maintain a changes list, with the hope that we might be able to see what's been changed and maybe help clients find where they're up to...

added changes markdown

---

types/bellatrix/block.yaml
types/capella/block.yaml

Fix: typos

---

apis/beacon/light_client/bootstrap.yaml
apis/beacon/light_client/finality_update.yaml
apis/beacon/light_client/optimistic_update.yaml
apis/beacon/light_client/updates.yaml
beacon-node-oapi.yaml
types/altair/light_client.yaml
types/bellatrix/transactions.yaml
types/capella/execution_payload.yaml
types/capella/light_client.yaml
types/capella/transactions.yaml

Implements the light client data format for Capella:
- https://github.com/ethereum/consensus-specs/pull/3151

support Capella LC data

---

apis/eventstream/index.yaml

Related to https://github.com/ethereum/beacon-APIs/issues/349, clarify what 'valid' means in the definition of all SSE topics except the block topic

Specify 'valid' gossip condition of SSE topics

---

types/api.yaml

Set DepositSnapshotResponse.finalized minItems=0 and maxItems=32

---

types/electra/withdrawal.yaml

Needs to wait for https://github.com/ethereum/consensus-specs/pull/4043

Rename PendingPartialWithdrawal field (index -> validator_index)

---

types/deneb/block.yaml
types/deneb/execution_payload.yaml
types/deneb/state.yaml
types/phase0/deposit.yaml

Closes https://github.com/ethereum/beacon-APIs/issues/514, see issue for more details.

Fix discrepancies between api schema definition and CL spec type(s)

---

apis/beacon/states/validator_identities.yaml

Closes https://github.com/ethereum/beacon-APIs/issues/532

Clarify handling of empty array for validator identities api

---

apis/validator/aggregate_and_proofs.v2.yaml
apis/validator/sync_committee_contribution_and_proof.yaml

These endpoints allow to submit a list of items and should support returning individual failures in error response.

Update error response of validator publish endpoints
