apis/validator/beacon-node-oapi.yaml
- Included the Attestation object in the schema.
- Updated the validator functions to GET and POST full Attestation objects, instead of IndexedAttestations.
- Updated POST request for block and attestation functions, to have the data expressed as JSON in the requestBody, rather than in the parameters as it was previously.
=> Updated IndexedAttestation to Attestation.

apis/validator/beacon-node-oapi.yaml
I'm primarily adding this endpoint as it extremely useful for validator clients to check their details and see if they are no longer active validators (slashed).
=> Add endpoint to get validator details

apis/beacon/basic.md
Adds a markdown document describing a basic beacon API that provides block, state, head and network information.
In the short term, clients need to interoperate and it would be helpful if they implemented standard, human-readable APIs so we don't need to go scrounging through logs to find simple things. Also, so people can build tools that can assess our interoperability foo.
In the long term, it'd be great if clients standardize upon API functionality to help make a unified developer ecosystem. Maybe this document can be the basis for this standardization effort.
What this is:
- Testing the waters to try and find a good format that is:
- Easily maintainable (i.e., easy to read and modify the source).
- Not going to require lots of work whenever the spec data structures change.
- Well …
=> Basic Beacon API

apis/validator/beacon-node-oapi.yaml
This enables users to enter any public BN api url in swagger UI in this repo to get data right here in browser.
=> Enable dynamic BN url

apis/validator/beacon-node-oapi.yaml, types/block.yaml, types/eth1.yaml, types/misc.yaml, types/operations/attestation.yaml, types/operations/attester_slashing.yaml, types/operations/deposit.yaml, types/operations/proposer_slashing.yaml, types/operations/voluntary_exit.yaml, types/state.yaml, types/validator.yaml
Notable changes:
- genesis endpoint returns "genesis_validator_root" so validator can construct domains for signatures
- removed "block_proposal_slot" from `AttesterDuty` (not sure how that was forgot there)
=> 0.11.1 types

types/primitive.yaml
The maximum value for uint64 is « 2^64–1 = 18446744073709551615 », previous example was not correct.
=> Fix Uint64 example

apis/node/health.yaml
All of the operations in the `/node/*` group prepend the HTTP method type used in their operation ID, except for `/node/health`. This makes the `/node/health` operationId consistent with the others.
=> Use a consistent operationId for /node/health

types/attestation.yaml, types/block.yaml, types/primitive.yaml, types/state.yaml
Remove all optional format specification for string because:
- Non-ambiguous hex format with length and prefix is already specified in the pattern.
- Bytes ties to base64 encoding instead of hex as per the Open Api Spec.
- Byte is a custom format.
Close #49
=> Remove optionals byte / bytes / hex format

apis/validator/beacon_committee_subscriptions.yaml, beacon-node-oapi.yaml, validator-flow.md
* change `subscribeToBeaconCommitteeSubnet` to `prepareBeaconCommitteeSubnet`. This is called regardless of `is_aggregator` to ensure that the BN has a signal to find peers of that particular subnet
* Note, many BN implementations attempt to just pro-actively have a diverse set of attnet peers, but having the ability to signal particular subscriptions provides flexibility in BN implementation and allows for BN to be extra certain to have the proper subscriptions.
* update and cleanup validator flow doc
=> update validator subnet subscriptions and validator flow doc

apis/eventstream/index.yaml, beacon-node-oapi.yaml
Assumed implementation is server sent events.
Since this is last missing method from WG proposal, this resolves #37 and resolves #25 and resolves #31
=> Add eventstream api

apis/beacon/blocks/header.yaml
I noticed this field is missing in `beacon/headers/{block_id}` but present in `beacon/headers`. I assume it's supposed to be in both places, please correct me if I'm wrong :)
=> Add root field to /beacon/headers/{block_id}

types/validator.yaml
This PR adds the `validator_index` field to the response of `GET /eth​/v1​/validator​/duties​/attester​/{epoch}`.
When consuming this API (writing tests) I noticed that consumers query via `validator_index`, but don't get it back in the response. 
Without the `validator_index` field in the response, consumers must maintain a mapping of `pubkey -> validator_index` on-hand if they wish to match the response to their request.
=> Add `validator_index` to `...duties/attester...`

types/block.yaml
This PR changes the `BeaconBlockBody` schema to use a `SignedVolnutaryExit` instead of a `VoluntaryExit` as all elements in a block should be signed.
=> Change BeaconBlockBody to use SignedVoluntaryExit

types/p2p.yaml
in line with a discussion on discord, Teku is not currently able to supply the ENR for peers, because libp2p is kept quite separate from discovery.
There's still a lot of helpful context in the peers list without ENR, so making ENR nullable will keep everything 'correct'.
=> make ENR nullable in peers response

apis/validator/beacon_committee_subscriptions.yaml, types/validator.yaml
Here I've added `committees_at_slot` which corresponds to the function parameter with the same name in [compute_subnet_for_attestation](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/validator.md#broadcast-attestation).
The `committees_at_slot` value is is the count of committee indices for attestation a given slot. It is derived purely from the active validator count and some constants.
The `committees_at_slot` is a piece of information that:
1. Is trivial for the BN to compute during `/eth/v1/validator/duties/attester/{epoch}`.
1. Is required during edge-cases in `/eth/v1/validator/beacon_committee_subscriptions` and is *not* trivial to compute then.
Both (1) and (2) require access to the shuffling. We already must load the shuffling to serve (1) but this is not true for …
=> Add committees_at_slot

types/validator.yaml
This adds the validator index to proposer duty return information, so that similar to attester duties they can be referenced by index rather than public key if desired.
=> Add validator index to proposer duties.

apis/validator/duties/proposer.yaml
'scheduled' is probably a more apt description of the proposer duties than 'supposed'. minor PR to suggest this description change.
=> update description of proposer duties

apis/beacon/states/validator_balances.yaml, beacon-node-oapi.yaml, types/api.yaml
This patch adds the validator balances endpoint `/eth/v1/beacon/states/{state_id}/validator_balances`  Its purpose is to fetch validator balance at a given epoch separate from the entire validator structure.
Rationale behind this being a separate endpoint is that historical data on a validator is, in general, not a lot of use; the current state for validators provides all of the prior state of interest for most use cases.  Having to fetch or recreate the entire validator structure for multiple epochs, when all a user wants is to obtain a history of their balance, can lead to a lot of wasted CPU time (at least it does with the current non-standard APIs on beacon node implementations).
=> Add validator balances endpoint

apis/eventstream/index.yaml
The `eventstream` `chain_reorg` message had fields `old_head_state` and `new_state_head`.  The latter should be `new_head_state`.
This PR fixes the above.
=> Rename new_state_head to new_head_state

apis/eventstream/index.yaml
Add the eventstream endpoint to the list of validatorRequiredApi endpoints.
Without this endpoint, the validator client won't see re-orgs, and won't know duties need to be fetched again, so I'm fairly sure it belongs in the required set.
=> Add eventstream to the ValidatorRequiredApi list.

apis/beacon/blocks/attestations.yaml, apis/beacon/blocks/block.yaml, apis/beacon/blocks/blocks.yaml, apis/beacon/blocks/header.yaml, apis/beacon/blocks/headers.yaml, apis/beacon/blocks/root.yaml, apis/beacon/pool/attestations.yaml, apis/beacon/states/committee.yaml, apis/beacon/states/finality_checkpoints.yaml, apis/beacon/states/fork.yaml, apis/beacon/states/root.yaml, apis/beacon/states/validator.yaml, apis/beacon/states/validator_balances.yaml, apis/beacon/states/validators.yaml, apis/debug/state.yaml, apis/eventstream/index.yaml, apis/node/peer.yaml, apis/validator/duties/attester.yaml, apis/validator/duties/proposer.yaml
This adds a response code 400 for all endpoints that have an input.  It allows it to be returned when the input data is in some way malformed.
Note that there is a difference between this and 404.  If you asked for block 5 and block 5 doesn't exist you would expect a 404.  If you asked for block foo you would expect a 400, as 'foo' is not a valid block number.
=> Add return code 400 for malformed input

apis/validator/duties/attester.yaml
As per #92 this changes the method to fetch attester duties from a GET to a POST.
The body of the request is a simple array of quoted validator indices _e.g._  `["1","2","3"]`
=> Change get attester duties method to POST

apis/config/spec.yaml
This PR adds the minimal validator tag to the spec endpoint.  This tag is required so that validator clients can fetch required configuration parameters (domains, times, _etc._).
It also fixes the link to the configuration in the specs repository, and clarifies that numbers should be quoted.
=> Add minimal tag to spec endpoint.

apis/beacon/states/committee.yaml, beacon-node-oapi.yaml
As per #108, this moves the optional `epoch` parameter from being a path parameter to a query parameter.  It also expands on the use of other query parameters as filters.
=> Make epoch parameter query rather than path

types/validator.yaml
As per @realbigsean this renames a field in `SignedAggregateAndProof` to match that in the official spec.
Fixes #106
=> Rename 'attestation' to 'aggregate' in SignedAggregateAndProof.

apis/validator/beacon_committee_subscriptions.yaml
Currently, at least two Eth2.0 clients (Lighthouse and Teku) require a validator index to be submitted along with the validator subscriptions API call. 
As pointed out in https://github.com/ethereum/eth2.0-APIs/issues/98 it may be possible to infer validator subscription counts from rates of subscription calls. The current API requires beacon nodes to do this. 
This PR supports both approaches, allowing any implementation to continue to infer validator counts by request rates but also supports Lighthouse's and Teku's current implementations by adding the validator index to the subscription call. This adds further information that allow the beacon node to know which exact validators are performing subscriptions. 
I think the overhead of adding a single uint64 is minimal compared to the …
=> Add validator index to validator subscriptions

apis/debug/state.yaml
Hopefully this is fairly clear - get by id should have a possible 404 code, as is done through most of the api.
=> add 404 code to getState as a possible response

apis/beacon/pool/attestations.yaml, beacon-node-oapi.yaml, types/http.yaml
At current the POST to `/eth/v1/beacon/pool/attestations` takes a single `Attestation`.  This PR proposes that this is changed to an array of `Attestation`s.
Rationale behind this is that beacon nodes often carry out a fair chunk of work to decide if to accept and/or broadcast an attestation.  This can include processing slots to obtain the relevant state, validating attestations against said state, and checking for the existence of subnets to broadcast the attestation.  These operations are commonly repeated for each attestation, which means that if a validator client has multiple attestations to submit for the same slot it can lead to more work, longer delays before broadcasting attestations, and ultimately a less efficient network.
To provide more concrete information related to the …
=> Move attestation submission to array.

apis/config/deposit_contract.yaml
Ethereum 1 chain ID is an anomaly in that it is presented as a number rather than a string.  This changes the value to be a uint64, and hence presented as a string, as per the conversation at https://discord.com/channels/595666850260713488/710831784991916072/775098382095482910.
=> Convert chain ID to uint64

apis/node/peer_count.yaml, apis/node/peers.yaml, beacon-node-oapi.yaml, types/p2p.yaml
Breaking:
peer.address -> peer.last_seen_p2p_address
Added clarifications and examples from #97 
@AgeManning is this ok?
resolves #97
=> Update peer endpoints

apis/beacon/states/validators.yaml, apis/debug/state.yaml
Similar to other endpoints pulling data from the beacon state, it's possible to not be able to retrieve a state when this request is made.
The state_id parameter is valid, but the state was not fetchable, (bytes32 didn't exist is one possibility, or the state is not retrievable for another reason)
This is distinct from a 400 error where it might be invalid input (state_id = "current" would be a 400), and it is useful to determine that the state isn't available vs. the user has requested invalid data.
=> add state not found possibility to state validators endpoint

apis/eventstream/index.yaml
I've specified that objects sent on SSE events must be valid. This PR serves to provide my suggestion (see code changes) and gather feedback from others.
- Allows for identifying faulty validators.
- Probably useful for research.
- Introduces the only scenario where we tell API consumers about invalid objects.
- If we go down this path, I think we must have a `valid` field on those objects.
- Potentially opens our API consumers up to damage from DoS attacks.
=> Specify that SSE events must contain valid objects

apis/eventstream/index.yaml, apis/validator/duties/attester.yaml, apis/validator/duties/proposer.yaml, beacon-node-oapi.yaml, types/primitive.yaml
Based on a proposal by @paulhauner (https://github.com/ethereum/eth2.0-APIs/issues/116#issuecomment-725866624), adds additional `dependent_root` fields which make it possible for validator clients to accurately determine when a chain reorg or block import has caused previously calculated duties to become invalid.  The previous approach only said to monitor `chain_reorg` events but didn't provide any guarantee that `chain_reorg` events would be published in all cases that could require invalidating duties.  See https://hackmd.io/kutQ7smJRZ-sJNSuY1WWVA#Why-head-must-be-published-for-empty-slots for an explanation of the scenario that is typically missed.
In this variant of the proposal, the `target_root` is included as a `dependent_root` metadata property for the attester and proposer …
=> Add dependent_root metadata to attestation and block duties

apis/config/deposit_contract.yaml
The description of `config/deposit_contract` is incorrect, as it talks about a genesis fork version, when it's the Eth1 chain ID which should be returned.
=> Fix description of config/deposit_contract

apis/node/syncing.yaml
Adds the `is_syncing: bool`field to the `../node/syncing` endpoint as per the reasons documented here: https://github.com/ethereum/eth2.0-APIs/issues/77#issuecomment-759164934
I would like to change `head_slot` to refer to *the block at the head of the canonical chain*,for consistency with the other uses of "head" in this API. I've left that out of this PR since that's a non-backwards-compatible change and I'd like to get this merged regardless of that change.
=> Add is_syncing to /node/syncing

apis/beacon/blocks/block.yaml
It useful to be able to fetch blocks as SSZ bytes, just as it is useful to be able to fetch states.
=> Allow the getBlock endpoint to return SSZ

apis/debug/state.v2.yaml, apis/debug/state.yaml, beacon-node-oapi.yaml, types/altair/block.yaml, types/altair/epoch_participation.yaml, types/altair/state.yaml, types/altair/sync_committee.yaml, types/primitive.yaml
In a similar design to GetBlockV2, GetStateV2 can return phase0 or altair states.
Also updated links in GetBlockV2 to refer to the newer spec, after validating there are no new changes.
=> Create v2 of getState, which supports an Altair state object being returned

apis/validator/beacon_committee_subscriptions.yaml, apis/validator/sync_committee_subscriptions.yaml, beacon-node-oapi.yaml, types/altair/sync_committee.yaml
https://hackmd.io/@QYHAVYiHRg65pdI_CEm7Eg/syncommitteeapi#POST-ethv1validatorsync_committee_subscriptions
notable differences:
- `sync_committee_index` became an array: sync_committee_indices, as multiple subnets per validator is possible.
- `is_aggregator` is not really needed in this instance as far as we can tell, and potentially won't be known at the time of making the subscription.
- added `until_epoch` so that the BN can unsubscribe based on this request.
=> add POST /eth/v1/validator/sync_committee_subscriptions

apis/validator/block.v2.yaml, beacon-node-oapi.yaml
Added a note on the v1 endpoint that it only supports phase0 block production
Added a note in the description of v2 to indicate the list of supported blocks will change over time as forks progress, hopefully setting the expectation that we're not creating a new api each time a fork happens.
=> add GET `/eth/v2/validator/blocks/{slot}`

apis/beacon/states/sync_committees.yaml, beacon-node-oapi.yaml, types/altair/sync_committee.yaml
add definition for sync_committees query of a state
basically adding https://hackmd.io/@QYHAVYiHRg65pdI_CEm7Eg/syncommitteeapi#GET-ethv1beaconstatesstate_idsync_committees to the spec
Names were changed slightly to more closely match the state object structure.
=> GET `/eth/v1/beacon/states/{state_id}/sync_committees`

apis/beacon/blocks/blocks.yaml
Given the discussion is leaning towards a POST that takes no indicators for which fork the block is, it would be simple to extend the existing POST to also accept altair blocks.
This PR demonstrates the concept for discussion, as an alternative to #141
=> POST `/eth/v1/beacon/blocks` for altair

apis/validator/sync_committee_contribution.yaml, beacon-node-oapi.yaml, types/altair/sync_committee.yaml
basically add https://hackmd.io/@QYHAVYiHRg65pdI_CEm7Eg/syncommitteeapi#GET-ethv1validatorsync_committee_contribution1 to standard api spec
re-uses the sync committee contribution description made in #137
in the hackmd there's no mention of a signature, but this object without the signature would be not particularly useful, so i've used the defined sync committee contribution in preference, hopefully that's what's needed.
=> GET `/eth/v1/validator/sync_committee_contribution`

apis/validator/duties/sync.yaml, beacon-node-oapi.yaml, types/validator.yaml
create a spec for sync committee duties for altair.
I'm open to making this more clearly altair specific, for now I've worked it into the typing information.
Basically I transcribed @mcdee hackmd from https://hackmd.io/@QYHAVYiHRg65pdI_CEm7Eg/syncommitteeapi#POST-ethv1validatordutiessyncepoch
=> add `/eth/v1/validator/duties/sync/{epoch}`

apis/beacon/blocks/block.v2.yaml
- blocks will be able to be returned as ssz bytes.
=> allow v2 block api to accept content type header

types/p2p.yaml
- Added as an optional field, it's only required once we hit altair and this will maintain compatibility with the current interface.
=> add syncnets to identity metadata for altair

apis/config/spec.yaml
Add details about exactly which values should be included in the /config/spec endpoint.  Also add example output showing format of each data type and values that change across forks.
=> Clarify spec endpoint values.

apis/validator/duties/attester.yaml
Currently the description of `dependent_root` is incorrectly placed inside the `event.block otherwise` list element.
=> Move description of `dependent_root` into new paragraph

apis/eventstream/index.yaml
This adds the `contribution_and_proof` event to the `events` endpoint.  It allows clients to listen for sync committee contributions.
Whilst we are here, this also standardizes the format of the events provided in the examples.
=> Contribution_and_proof event

apis/config/fork_schedule.yaml
This updates the description of the config/fork_schedules endpoint to state that all forks should be returned rather than just the upcoming forks.
=> Update description of fork schedule.

types/altair/sync_committee.yaml
The altair response schema for https://ethereum.github.io/eth2.0-APIs/#/Debug/getStateV2 fields `current_sync_committee` and `next_sync_committee` are not in line with the spec. `pubkeys` length is 1024 and `pubkey_aggregates` is an array, whereas https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/beacon-chain.md#synccommittee specifies `pubkeys` of length 512 (`SYNC_COMMITTEE_SIZE`) and an `aggregate_pubkey` field which is a single public key.
=> Make sync committee type conform to spec

apis/beacon/states/validator.yaml, apis/beacon/states/validator_balances.yaml, apis/beacon/states/validators.yaml
Validator ID in a query parameter should not be required to be on the g2 curve to be valid, any bytes48 should be allowed to be queried on.
Reading in any bytes48 without validating against the g2 curve will reduce overheads of parsing large lists, and given that valid missing keys are just not returned, there are no real negatives to querying a key that will definitely be missing.
fixes #183
=> Clarify validator id as any bytes48

README.md
This one took me a while to figure out. Both Chrome and Firefox wouldn't display changes (even with Ctrl+Shift+r and Shift+F5).
=> Add note about caching

apis/validator/prepare_beacon_proposer.yaml, beacon-node-oapi.yaml, types/primitive.yaml
This adds the `prepare_beacon_proposer` endpoint, required for the merge.  It follows on from discussion at https://github.com/sigp/lighthouse/issues/2715
There has been some debate over how to handle the fact that this information is not persistent over beacon node restarts.  The three options suggested are:
- implict expiry _e.g._ the information expires 2 epochs after being provided or when the beacon node restarts, whichever is earlier
- explicit expiry _e.g._ each request object has an `until_epoch` field such that the information expires at the given epoch or when the beacon node restarts, whichever is earlier
- no expiry _i.e._  the information expires when the beacon node restarts
Given that the first two options still lose the data when the beacon node restarts the initial …
=> Addition of prepare_beacon_proposer endpoint.

README.md
I noticed after #188 was merged that the usage notes I had provided seemed glued to the NodeJS instrucutions, rather than applied to Python as well.
=> Add "usage" section

.github/workflows/deploy.yaml, .github/workflows/main.yml, .github/workflows/release.yaml, .spectral.yml, README.md, params/index.yaml
There was an increasing number of flaky ci, this should hopefully fix it as we are running the latest version of npm packages instead of deprecated ones in docker actions.
=> Replace deprecated docker actions and use npm packages directly

apis/validator/aggregate_attestation.yaml, apis/validator/sync_committee_contribution.yaml, beacon-node-oapi.yaml
There are times when an aggregate or contribution is requested by a VC, and the beacon node simply doesn't have any information to return.
Returning 400 'bad request' is probably excessive in this case, the request may be perfectly valid and it's just that the BN wasn't able to respond with data.
We believe that a 404 in these cases would be warranted and allow us a better idea of actual bad requests vs. no data being found at the BN.
=> Add not found responses for aggregates and contributions

apis/eventstream/index.yaml
The addition of execution_optimistic as an additional field isn't allowed by the event stream spec. It needs to be added into the `data:` content.
=> Move execution_optimistic into the event data

beacon-node-oapi.yaml
As per https://github.com/ethereum/beacon-APIs/pull/190#issuecomment-1029912550 this provides some explanation about the difference between data and metadata, endpoint versions, and when an endpoint version should change.
These rules have been implicit, and as such poorly defined, until now.  I have inferred the rules from actions we have carried out in the past, however as they are now being made explicit it would be good for someone from each client team to take a look at them and confirm they are happy with them.
=> Additioinal information about API endpoint versions, data and metadata.

apis/node/syncing.yaml
In Bellatrix, nodes that are optimistically tracking head will be responding with is_syncing as true, but be optimistically tracking head.
Added a new field to be able to determine that a node is optimistically tracking the head of the chain.
=> add is_optimistic to getSyncingStatus response

validator-flow.md
The link for the validator-flow.md was broken on the rendered site because Jekyll (which currently renders the HTML) does not detect the markdown document as a valid page without "front matter".
This PR adds the required data.
=> Fix broken link by making document into Jekyll page

.github/workflows/main.yml, .gitignore, README.md, apis/beacon/blocks/blinded_blocks.yaml, apis/beacon/blocks/block.v2.yaml, apis/beacon/blocks/blocks.yaml, apis/validator/blinded_block.yaml, apis/validator/block.v2.yaml, beacon-node-oapi.yaml
Block production and signed block consumption should allow SSZ encoding to help us reduce overheads on for api consumers.
Fallbacks will likely remain json for clients anyway if they're not reading the headers, but if they do read the headers then there's big performance gains to be had in returning / consuming SSZ.
At a later time it may be worth also accepting SSZ on other endpoints also.
=> Add ssz format for block production.

beacon-node-oapi.yaml
The repo is licensed under CC0-1.0, but the oapi is showing it's licensed under Apache 2.0. I updated the oapi spec to be CC0-1.0.
=> Make oapi license cc0

README.md, apis/beacon/states/fork.yaml, apis/config/spec.yaml, types/altair/block.yaml, types/altair/state.yaml, types/altair/sync_aggregate.yaml, types/attestation.yaml, types/attester_slashing.yaml, types/bellatrix/block.yaml, types/bellatrix/execution_payload.yaml, types/block.yaml, types/deposit.yaml, types/eth1.yaml, types/misc.yaml, types/p2p.yaml, types/proposer_slashing.yaml, types/state.yaml, types/validator.yaml, types/voluntary_exit.yaml, validator-flow.md
There are still many `eth2.0` references in this repo. For consistency, I've modified the outdated `eth2.0-specs` links to `consensus-specs` and in prose `Eth2.0` to `CL`.
=> Replace `eth2.0` with consensus layer

apis/validator/register_validator.yaml, beacon-node-oapi.yaml, types/registration.yaml
This is another take on #206.
Rather than extending `prepare_beacon_proposer`, in this PR we create a new, separate endpoint `register_validator`. This addresses two pieces of feedback raised against the extension:
1) `prepare_beacon_proposer` performs a critical operation and probably shouldn't be encumbered by any additional responsibilities
2) `register_validator` will likely be executed on a different rhythm than `prepare_beacon_proposer`, so it feels more appropriate to separate out that logic
--
Now a short recap on why it's important this data is sent to the beacon node in the first place.
After the merge, validators will want to extract MEV from blocks. The mechanism that will facilitate this extraction a network of external builders. These builders will provide …
=> Add `register_validator` endpoint

apis/validator/aggregate_attestation.yaml, apis/validator/attestation_data.yaml, apis/validator/sync_committee_contribution.yaml
This PR ensures that the BN does not produce attestations, aggregate attestations or sync committee contributions that refer to optimistic blocks.
Attesting to an optimistic block is *very bad* and could result in finalizing an invalid execution payload. The changes in this PR mean that the VC doesn't need to check the optimistic status for each object. This saves calls to the API and also protects against faults in VC implementations.
Although sync committee contributions to optimistic blocks couldn't result in an invalid finalized block, it could cause havoc for light clients.
=> Don't produce messages for optimistic blocks

apis/validator/blinded_block.yaml
The Eth-consensus-version wasn't listing in the headers for a 200 response like it was in get new block, so making it consistent here.
=> fix eth-consensus-version for blinded_block response

apis/config/spec.yaml
The example section for the `/eth/v1/config/spec` endpoint does not have the correct padding and it gets [rendered](https://ethereum.github.io/beacon-APIs/#/Config/getSpec) as:
```
{
"DEPOSIT_CONTRACT_ADDRESS": ""
}
```
instead of:
```
{
"data": {
"DEPOSIT_CONTRACT_ADDRESS": ""
}
}
```
=> Fix config spec schema example

types/altair/block.yaml, types/bellatrix/block.yaml, types/block.yaml
This PR uses the `Graffiti` primitive in the `BeaconBlock` objects.
=> Use the correct primitive for Graffiti

apis/validator/block.v2.yaml
Recently I've been speculatively creating blocks using the `/eth/v2/validator/blocks/{slot}` endpoint, polling the endpoint live at every slot.
Some beacon node implementations verify the `randao_reveal` signature when this endpoint is used, which causes speculative block proposal to fail (because the private key for the true `proposer_index` is not known).
A few months ago I added an optional `verify_randao` parameter to disable the verification in Lighthouse: https://github.com/sigp/lighthouse/pull/3116. Recently I've discovered that Nimbus have started to verify the `randao_reveal` by default too, so I'd like to implore them to adopt the same parameter.
As far as I know the other clients (Teku/Prysm/Lodestar) don't verify the `randao_reveal` currently, so I think it would be acceptable …
=> Optional randao verification when producing blocks

types/altair/state.yaml, types/altair/sync_aggregate.yaml, types/attestation.yaml, types/bellatrix/state.yaml, types/primitive.yaml, types/state.yaml
From https://github.com/ethereum/beacon-APIs/pull/234#issuecomment-1232705540
Add consistently `format: hex` to all strings.
```
swagger-cli bundle ./beacon-node-oapi.yaml -r -t yaml -o ./deploy/beacon-node-oapi.yaml
cd deploy
python -m http.server 8080
```
=> Add format hex to hex strings

apis/beacon/blocks/blocks.yaml, beacon-node-oapi.yaml
Mistakenly removed in #218, this PR puts back the /eth/v1/beacon/blocks POST.
thanks for raising issue @michaelsproul
=> Added POST /eth/v1/beacon/blocks back in place

apis/beacon/blocks/blinded_block.yaml, beacon-node-oapi.yaml
This PR adds a new endpoint analogous to `/eth/v2/beacon/blocks/{block_id}` that serves _blinded_ blocks rather than full blocks. The new endpoint is `/eth/v1/beacon/blinded_blocks/{block_id}`.
We already have other endpoints for creating new blinded blocks and POSTing signed blinded blocks back to the BN, so this PR completes the trilogy.
There are several reasons why such an endpoint is useful and desirable:
- Most consensus clients do not store full blocks with execution payloads in their databases. Fetching a finalized blinded block can be done more quickly and efficiently than serving a full block which has had its payload pruned and would require a call to the EL to reconstruct.
- Blinded blocks contain a lot of useful information that isn't in block headers, including the execution …
=> Endpoint for fetching blinded blocks

apis/beacon/light_client/bootstrap.yaml, apis/beacon/light_client/finality_update.yaml, apis/beacon/light_client/optimistic_update.yaml, apis/beacon/light_client/updates.yaml, apis/eventstream/index.yaml, beacon-node-oapi.yaml, params/index.yaml, types/altair/light_client.yaml
Introduces additional REST endpoints for light client sync, compatible with the libp2p specification defined in `ethereum/consensus-specs`: https://github.com/ethereum/consensus-specs/blob/v1.2.0-rc.3/specs/altair/light-client/p2p-interface.md
Endpoints are defined to be fork-aware to allow potential optimizations such as including EL block hash into `BeaconBlockHeader` in the future.
The `getLightClientUpdatesByRange` endpoint is a new kind of endpoint, as it introduces the concept of list responses. Each list item could potentially be of a different fork. Likewise, for the events stream, the fork may update between events. Both the list response and the event are additionall wrapped with a per-item `version` indicator in JSON. For SSZ, the list items are encoded as …
=> Define endpoints for light client sync

apis/beacon/blocks/attestations.yaml, apis/beacon/blocks/blinded_blocks.yaml, apis/beacon/blocks/block.v2.yaml, apis/beacon/blocks/block.yaml, apis/beacon/blocks/header.yaml, apis/beacon/blocks/headers.yaml, apis/beacon/blocks/root.yaml, apis/beacon/genesis.yaml, apis/beacon/pool/attestations.yaml, apis/beacon/pool/attester_slashings.yaml, apis/beacon/pool/proposer_slashings.yaml, apis/beacon/pool/voluntary_exists.yaml, apis/beacon/states/committee.yaml, apis/beacon/states/finality_checkpoints.yaml, apis/beacon/states/fork.yaml, apis/beacon/states/root.yaml, apis/beacon/states/sync_committees.yaml, apis/beacon/states/validator.yaml, apis/beacon/states/validator_balances.yaml, apis/beacon/states/validators.yaml, apis/debug/state.v2.yaml, apis/eventstream/index.yaml, apis/node/peer.yaml, apis/validator/duties/attester.yaml, apis/validator/duties/proposer.yaml, apis/validator/duties/sync.yaml, apis/validator/prepare_beacon_proposer.yaml
The build step done on build resolves all $ref references.
https://github.com/ethereum/beacon-APIs/blob/9cab46ad3c94a4a2779b42fa21f6bb1955b60b56/.github/workflows/main.yml#L18
If a property is specified both in the $ref and the existing schema the latter overrides $ref without needing allOf syntax. So
- If you need to override the description property or add a new example, no need for allOf
- If you need to merge object "properties" you need allOf to perform deep merging at runtime
=> Remove unnecessary allOf from error reponse schemas

apis/validator/blinded_block.yaml
Follow-up to https://github.com/ethereum/beacon-APIs/pull/222.
The endpoint for producing blinded blocks needs the `skip_randao_verification` parameter for the same reasons as the regular endpoint (see #222). It was an oversight on my part to not include it from the beginning.
The parameter is already implemented in Lighthouse (because code is shared with the non-blinded backend), and it seems that in Nimbus the blinded endpoint is not yet supported. Other clients don't verify RANDAO reveals during block production (yet) and do not need to implement the flag or can implement it as a no-op.
=> Add `skip_randao_verification` for blinded blocks

apis/beacon/states/randao.yaml, beacon-node-oapi.yaml
Add an endpoint to fetch the RANDAO mix from a given state at some epoch.
The endpoint path is `/eth/v1/beacon/states/{state_id}/randao`.
With the merge the RANDAO mix has taken on increased significance, as it is embedded in execution payloads and available in the EVM.
Currently for tools that want to access the `prev_randao` from outside the beacon node for the purposes of payload construction or validation, they must load an entire beacon state using the debug endpoint. This is prohibitively slow for something that _should_ be fast with the right API.
With this API, they can immediately get access to the correct `prev_randao` value using `/eth/v1/beacon/states/head/randao` prior to block construction (or can use the `state_id` corresponding to the parent block).
=> Endpoint for state RANDAO mix

apis/validator/register_validator.yaml
Clarify in the `registerValidator` description that registrations for `exited` or unknown validators will not be sent to the builder network.
Related to https://github.com/flashbots/mev-boost/issues/245
=> Registrations for exited or unknown validators will not be sent to the builder network

apis/node/health.yaml
When specified, the server will return the value in the query parameter instead of 206, if the server is syncing.
fixes #147
=> Add syncing_status query parameter to GetHealth

apis/beacon/blocks/blinded_block.yaml, apis/beacon/blocks/blinded_blocks.yaml, apis/beacon/blocks/block.v2.yaml, apis/beacon/blocks/blocks.yaml, apis/beacon/pool/bls_to_execution_changes.yaml, apis/debug/state.v2.yaml, apis/eventstream/index.yaml, apis/validator/blinded_block.yaml, apis/validator/block.v2.yaml, beacon-node-oapi.yaml, types/bls_to_execution_change.yaml, types/capella/block.yaml, types/capella/execution_payload.yaml, types/capella/state.yaml, types/capella/transactions.yaml, types/capella/withdrawals.yaml, types/withdrawal.yaml
Update existing types to capella spec, use them where appropriate (blocks, execution payloads).
Add `BLSToExecutionChange` type and related types and endpoints.
Spec references point to master at current, will change once a tagged capella release is made.
=> Add capella types and endpoints.

types/altair/state.yaml, types/bellatrix/state.yaml, types/capella/state.yaml, types/state.yaml
When rendering example data, huge lists will cause the page to stop responding.
This is particularly evident in BeaconState, where our limits are huge, and we only specify a maximum.
The limits are functionally huge so I removed them, as setting minItems didn't seem as effective in keeping the swagger page alive...
fixes #257
=> Remove maxItems from lists in debug/states

apis/beacon/blocks/attestations.yaml, apis/beacon/blocks/blinded_block.yaml, apis/beacon/blocks/block.v2.yaml, apis/beacon/blocks/header.yaml, apis/beacon/blocks/headers.yaml, apis/beacon/blocks/root.yaml, apis/beacon/states/committee.yaml, apis/beacon/states/finality_checkpoints.yaml, apis/beacon/states/fork.yaml, apis/beacon/states/randao.yaml, apis/beacon/states/root.yaml, apis/beacon/states/sync_committees.yaml, apis/beacon/states/validator.yaml, apis/beacon/states/validator_balances.yaml, apis/beacon/states/validators.yaml, apis/debug/state.v2.yaml, apis/validator/duties/attester.yaml, beacon-node-oapi.yaml, types/primitive.yaml
Whether or not a request pertains to the finalized section of the chain (per the view of the client fork choice) is somewhat cumbersome to discover.
This PR adds a boolean that allows clients to distinguish a response that has been finalized and thus is unlikely to change from one that may still change over time (specially when using slot-based requests).
A flag like this can also be used for the purpose of verifying that a checkpoint root indeed is part of chain history and is likely to remain as such, as discussed in
https://github.com/ethereum/beacon-APIs/pull/226
=> Add `finalized` flag to chain data requests

apis/validator/liveness.yaml, beacon-node-oapi.yaml
https://github.com/ethereum/beacon-APIs/pull/131 introduced a new liveness endpoint - the request is similar to attester duties in that we query a list of validators for data pertaining to a particular epoch - as such, it seems reasonable to keep the two requests similar in terms of their URL/postdata structure.
=> Give liveness epoch same "shape" as attester duties

apis/beacon/deposit_snapshot.yaml, beacon-node-oapi.yaml, types/api.yaml
Adds the endpoint for downloading the [`EIP-4881`](https://eips.ethereum.org/EIPS/eip-4881#specification) Deposit Tree Snapshot during weak subjectivity sync.
=> Endpoint for EIP-4881 Deposit Contract Snapshot

types/capella/state.yaml
https://github.com/ethereum/consensus-specs/pull/3068 changed the structure of the beacon state. This PR updates the schema accordingly.
=> Align Capella state with spec

types/capella/block.yaml
Add the `bls_to_execution_changes` item to blinded Capella beacon blocks.
=> Add bls_to_execution_changes to blinded blocks.

.github/workflows/deploy.yaml, README.md, index.html
Avoid using the CORS proxy by bundling the releases into the github pages deployment.
- pages deployed [example](https://savid.github.io/beacon-APIs/)
- deploy action run [example](https://github.com/Savid/beacon-APIs/actions/runs/3690288991)
resolves #280
=> feat(ci): use same origin for oapi definitions

apis/beacon/rewards/attestations.yaml, types/rewards.yaml
There was an extra layer of unnecessary array nesting in the attestation rewards response:
```json
{
"data": [
{"ideal_rewards": [], "total_rewards": []}
]
}
```
The `data` list should always have 1 element, because the real lists are contained in `ideal_rewards` and `total_rewards`. Therefore this structure is more appropriate:
```json
{
"data": {"ideal_rewards": [], "total_rewards": []}
}
```
This is already implemented by Lighthouse in https://github.com/sigp/lighthouse/pull/3822.
=> Remove array from attestation rewards response

types/fork_choice.yaml
All enums are lower case but this has been merged as UPPER CASE.
=> Make fork choice validity enum lower case

apis/builder/states/expected_withdrawals.yaml, beacon-node-oapi.yaml
Added into a new route, `/eth/v1/builder`, as it's different to the existing beacon state fetch paradigm, and a new Tag for builders seems appropriate.
This endpoint is probably suited to allowing for returning SSZ via octet-stream also, so added that in. The idea would be similar to blocks, it would just return the data object as the SSZ result.
It would be possible to add withdrawals_root, but it'd be at the same level as finalized, so it'd be a little less clean. I've left that out for now.
Fixes #301.
=> Added withdrawals endpoint to fetch withdrawals from a parent state

apis/eventstream/index.yaml
Closes #244.
Define a new server sent event (SSE) for payload attributes.
The difficult part of specifying this event was deciding on an encoding for the payload attributes. Payload attributes presently only exist in the `execution-specs` repo where they are always encoded with `camelCase` idents and big-endian hex integers. We have two options for encoding them here:
1. Use the `execution-apis` encoding and break consistency with the rest of `beacon-apis`.
2. Define a new encoding for payload attributes here in order to maintain consistency.
There are pros and cons in favour of each approach. Option (1) potentially minimises the number of encodings that clients need to maintain for the payload attributes data structure, which could be good for implementation complexity. On the other …
=> SSE for payload attributes

apis/eventstream/index.yaml
fixing a typo in the example that clarifies the response as well.
related https://github.com/ethereum/beacon-APIs/pull/305
=> typo fix in SSE for payload_attributes

apis/validator/sync_committee_selections.yaml
Same as for `submitBeaconCommitteeSelections`,  `submitSyncCommitteeSelections` API is not implemented by a consensus client and should return 501.
https://github.com/ethereum/beacon-APIs/blob/f087fbf2764e657578a6c29bdf0261b36ee8db1e/apis/validator/beacon_committee_selections.yaml#L40-L41
=> Add 501 error response to submitSyncCommitteeSelections

beacon-node-oapi.yaml
Update version for release, and referencing 1.3.0 of consensus-spec.
=> Updated version for v.2.4.0 release of beacon-apis.

CHANGES.md, types/capella/historical_summary.yaml, types/capella/state.yaml
In Capella, historical_roots has been replaced by historical_summaries, but this was not reflected in our state object.
Fixes #315
=> Added historical summaries to Capella beacon state.

apis/beacon/blocks/blinded_blocks.v2.yaml, apis/beacon/blocks/blocks.v2.yaml
Updated the `publishBlindedBlockV2` to use the `Deneb.SignedBlindedBlockContents` schema for Deneb.
I think the blob signing endpoints PR #302 was merged right after `publishBlindedBlockV2` was added in #317, and the `publishBlindedBlockV2` method was missing a schema change for Deneb.
=> Update publishBlindedBlockV2 request schema for Deneb

apis/beacon/blob_sidecars/blob_sidecars.yaml
Just noticed 2 minor typos in `getBlobSidecars`
=> Fix typos in getBlobSidecars

apis/eventstream/index.yaml, apis/validator/duties/attester.yaml, apis/validator/duties/sync.yaml, apis/validator/liveness.yaml, types/p2p.yaml
These didn't seem to match the warnings raised by @mcdee , but they were valid issues picked up in editor.swagger.io regarding `minItems` and `uniqueItems` needing to be an attribute of an array not an object, an issue with `nullable` usage that we had.
=> Fixed lint warnings

apis/beacon/states/validator_balances.yaml, apis/beacon/states/validators.yaml
I'd like to make the case for why these codes should be implemented-
1. The 400 description doesn't mention maxItems: `Invalid state or validator ID`, so a BN enforcing maxItems will potentially confuse a downstream system.
2. The BN isn't always directly responsible for responding to the downstream system- for example, nginx, cloudflare, haproxy, etc may return a 414 if the Request-Line is too long. Enshrining the 414 code in the spec serves as a signal to programmers of downstream systems that they ought to take care to handle those errors.
3. A client team developing both a VC and a BN may incorrectly assume that because their BN never returns a 414, they do not need to handle a 414 in the VC.
=> Use HTTP 414 status code for GET maxItems enforcement

apis/beacon/states/validator_balances.yaml, apis/beacon/states/validators.yaml
[RFC-7230](https://www.rfc-editor.org/rfc/rfc7230#section-3.1.1) recommends that the Request-Line component of an HTTP 1.1 request is limited to a minimum of 8000 bytes.
Each pubkey is 48 bytes binary, or 96 bytes hex encoded. Prefixing with `0x` adds two more bytes for 98.
All but the first pubkey are preceded by a comma, so with a limit of 64 we will have consumed 64*98+63 bytes, or 6335 bytes.
Factoring the length of these paths (we will assume the `state` is a stateRoot with 0x prefix, ie 66 bytes, to remain adequately pessimistic) we get 107 bytes for `validator_balances` and 99 for `validators`. We increase our consumption by 107 bytes to 6442 bytes.
Adding in some unavoidable bits and pieces from the RFC section on Request-Line-
- `?id=` = 6446
- `GET` = 6449
- `HTTP/1.1` = 6457
- …
=> Update validator key/index URI array limits

apis/beacon/states/sync_committees.yaml
I wasn't sure what the `validator_aggregates` were in the sync committee endpoint
@michaelsproul confirmed they are the sync subcommittee assignments and I have added this information to the API docs
=> expand sync committee docs

apis/beacon/blocks/blinded_blocks.v2.yaml, apis/beacon/blocks/blocks.v2.yaml
When initially adding eth-consensus-version to interfaces it wasn't able to be required due to backwards compatibility issues.
Given these interfaces are new, we should set it as a required header. This will simplify the determination of whether we're reading a deneb blockContents or a pre-deneb signed block.
Potentially we deprecate the other interface once deneb comes around, but that's up for discussion, and I'm not putting that into this PR, just making this header required for the new interfaces.
=> Made eth-consensus-version required on new blocks endpoints

apis/node/health.yaml
While implementing `syncing_status` query parameter (https://github.com/ethereum/beacon-APIs/pull/251), I noticed two issues with the current spec
1. Schema allows invalid http status codes (1-99), this will cause problems for most http servers
2. The API accepts user provided values but there is no error response for invalid values
=> Update syncing status requirements in getHealth

apis/validator/blinded_block.yaml, apis/validator/block.v3.yaml, beacon-node-oapi.yaml, types/primitive.yaml
As per #309 this adds a version 3 `block` endpoint that consolidates the current blinded and unblinded endpoints.  Features of this endpoint:
- a single endpoint to fetch blocks regardless of type
- allows the beacon node to decide (with help from the EL) if it should use MEV relays for execution payload
- provides the returned block's payload to the proposer
- metadata allows for simpler handling of decoding the returned data
=> Add block v3 endpoint.

apis/validator/block.v3.yaml
Casing of the JSON metadata for the v3 block API was in kebab case (as per headers) but should be in camel case as per all other JSON.
=> Fix casing of JSON metadata.

types/rewards.yaml
This PR adds the following fields to the `AttestationsRewards` response:
1. A `inactivity` field to both `ideal_rewards` and `total_rewards`.
2. A `inclusion_delay` field to `ideal_rewards`
Currently the inactivity penalties are not part of the `AttestationsRewards` response, and is something users of this endpoint (e.g. explorers) have expressed interests in. 
I thought about whether it makes sense to combine them into the current `source`, `target` and `head` fields, however I think there are a few reasons to keep them in a separate field:
- The extra penalty for missing attestations or being slashed during an inactivity leak doesn't really belong to any of those fields
- IMO it's more consistent with how they are grouped in the consensus spec …
=> Add `inactivity` and `inclusion_delay` fields to Attestation Rewards

README.md, beacon-node-oapi.yaml
Also tweaked the releasing section of the readme to better describe changing the info.version back after release is complete.
=> Updated info.version for release.

apis/validator/block.v3.yaml, beacon-node-oapi.yaml
In order to compare blocks coming from two sources, a validator client must consider both consensus and execution profit - without consensus reward information, the VC must fall back on unreliable heuristics that can be biased towards inefficient consensus packing, specially when execution payloads are the same which they are likely to be if the block producer is using the same mev relay for both beacon nodes.
The consensus computation is currently not a necessary part of block construction but given that blocks are constructed over a state, the information necessary to compute the is already present at block construction time.
This PR suggests a mandatory value to make validator client multiplexing easier at the expense of beacon node complexity - if instead it is optional, we are back …
=> blocksv3: add consensus value

apis/validator/beacon_committee_selections.yaml, apis/validator/sync_committee_selections.yaml
Update endpoint descriptions for the following selections endpoints:
* `/eth/v1/validator/beacon_committee_selections`
* `/eth/v1/validator/sync_committee_selections`
This PR updates selection endpoint descriptions to explicitly state when to call these endpoints:
- For sync committee selections, validator clients must query this endpoint at the start of each slot in the sync committee period.
- For beacon committee selections, validator clients must query this endpoint at the start of each epoch for attester duties in the current and next epochs.
Note: This change eliminates confusion among client teams implementing these endpoints on when to query the selection endpoints.
=> update selections endpoint description

apis/beacon/blocks/blinded_blocks.v2.yaml, apis/beacon/blocks/blocks.v2.yaml
It's mentioned in description that in case of broadcast validation failure we should return 400, but error codes description like "The `SignedBlindedBeaconBlock` object is invalid" confuses a bit. I've changed it to be more clear
=> Clarify broadcast validation failure in response code for publishBlockV2

types/validator.yaml
The missing `type: object` prevents generated JSON to be valid.
=> fix: add missing type property

.github/workflows/deploy.yaml
The [Checkout validator flow](https://ethereum.github.io/beacon-APIs/validator-flow.md) link is broken on the deployed [doc](https://ethereum.github.io/beacon-APIs/#/).
This is due to a file not being copied to the right folder during the deployment phase.
Note that this will only impact the deploy procedure. The right file should be copied on the `gh-pages` branch to fix on the live website.
=> Fix broken link in deployed doc

apis/validator/block.v3.yaml
the renaming of the `builder_comparision_factor` to `builder_boost_factor` was accepted in https://github.com/ethereum/beacon-APIs/pull/386 but all references weren't updated.
this PR just updates the references
=> chore: fix references of builder's comparision factor to boost factor

types/rewards.yaml
Both uint64 and int64 are defined are quoted numbers, fix examples to align with their type.
https://github.com/ethereum/beacon-APIs/blob/4882aa0803b622b75bab286b285599d70b7a2429/types/primitive.yaml#L32-L34
https://github.com/ethereum/beacon-APIs/blob/4882aa0803b622b75bab286b285599d70b7a2429/types/primitive.yaml#L40-L42
For reference Lighthouse stable quotes all integers in the rewards API
https://github.com/sigp/lighthouse/blob/441fc1691b69f9edc4bbdc6665f3efab16265c9b/common/eth2/src/lighthouse/attestation_rewards.rs#L8-L27
=> Quote uint64 and int64 examples

apis/eventstream/index.yaml, types/primitive.yaml
Based on discussion in https://github.com/ethereum/beacon-APIs/pull/395 it would be good if we could use  [ERC-55 mixed-case checksum address encoding](https://github.com/ethereum/ercs/blob/master/ERCS/erc-55.md) for execution addresses in beacon API spec.
If this gets merged we should also do the same to keymanager API spec ([types/eth_address.yaml#L2](https://github.com/ethereum/keymanager-APIs/blob/a8c45a15cf820a1a832eafaec1c64ea31ed6f2ca/types/eth_address.yaml#L2)). Builder API spec references [SignedValidatorRegistration](https://github.com/ethereum/builder-specs/blob/22a17d312bdd18aba59aaa536002553759a55c16/builder-oapi.yaml#L78-L79) from beacon API spec so we should be fine there (some example values could be updated)
=> Use ERC-55 mixed-case checksum address encoding for execution address

beacon-node-oapi.yaml
Require both execution payload value and consensus block value to be denominated in _wei_.
There are advantages to wei+gwei or wei+wei, and we just need to choose one. I've chosen to use the wei+wei option, because the consistency makes the API less confusing, and I think this trumps concerns about performance or unnecessary zero padding.
Closes #397
=> Clarify that payload & block values are in Wei

index.html
#414 broke the ethereum UI logo. This restores it.
**currently deployed**
**with this PR**
=> fix: restore ethereum logo

apis/beacon/blocks/blinded_block.yaml, apis/beacon/blocks/blinded_blocks.v2.yaml, apis/beacon/blocks/blinded_blocks.yaml, apis/beacon/blocks/block.v2.yaml, apis/beacon/blocks/blocks.v2.yaml, apis/beacon/blocks/blocks.yaml, apis/beacon/light_client/bootstrap.yaml, apis/beacon/light_client/finality_update.yaml, apis/beacon/light_client/optimistic_update.yaml, apis/beacon/light_client/updates.yaml, apis/debug/state.v2.yaml, apis/validator/blinded_block.yaml, apis/validator/block.v2.yaml, apis/validator/block.v3.yaml
`oneOf` is currently used the following way (except for `enums`):
* first element is an object from phase0
* then a couple of variations per fork, adding extra properties
So when an object from a later phase (e.g. `bellatrix`) has to be validated, it also matches the definition from`phase0`, .. (unless it's more complex than just new properties). 
Which is incorrect as oneOf must match a single definition.
What we want here is `anyOf`, that matches if one or more definitions matches.
=> fix: replace oneOf with anyOf

beacon-node-oapi.yaml
Bump version to 2.5.0 to start release process.
Based on https://github.com/ethereum/beacon-APIs/compare/v2.4.2...master there are no breaking changes.
=> Update info.version for v2.5.0 release

apis/node/health.yaml
The 206 return code for the node health endpoint does not take into account the situation where the consensus node may be synced by the execution node is optimistic.  Clarify that this situation should return the 206 status code.
=> Clarify use of 206 status code for node health.

apis/beacon/blob_sidecars/blob_sidecars.yaml
As noted in https://github.com/ethereum/beacon-APIs/issues/439 and after further [discussion on discord](https://discord.com/channels/595666850260713488/1227937241427611658), the rough consensus seems to be to add those metadata fields without bumping the api version, but to make them optional for now until all clients have updated their implementation.
Closes https://github.com/ethereum/beacon-APIs/issues/439
=> Add metadata fields to getBlobSidecars response

apis/validator/blinded_block.yaml, apis/validator/block.v2.yaml, apis/validator/block.v3.yaml, beacon-node-oapi.yaml, params/index.yaml
There are few issues the way current spec defined the `skip_randao_verification` parameter. As of my understanding that's the only boolean type path parameter defined in the spec, but we should follow the approach in this fix for any future case as well. 
The current spec says if you want to set this flag, don't set value. Which is not semantically possible as it's a query parameter, so eventually any value which is not set is considered as **empty string** from most HTTP request parser. 
Flags implies it's a boolean value, so eventually the spec says if you want to set this flag to **true** set it to am **empty string** value. Which is logically considered **false** on different dynamic programming languages, or in dynamic execution of a static languages. e.g. 
JS
```js
"" ? true : …
```
=> Improve the schema for skip_randao_verification flag type

CHANGES.md, apis/validator/aggregate_attestation.v2.yaml, apis/validator/aggregate_attestation.yaml, beacon-node-oapi.yaml, types/electra/attestation.yaml
`AttestationData` post-electra is committee-indifferent, and thus, the same `attestation_data_root` might be shared across different committees. 
An aggregator is only interested in attestations in its corresponding committee. `getAggregatedAttestationV1` might aggregate attestations from multiple committees since `committee_index` is not in its params. 
This PR adds `getAggregatedAttestationV2` to aggregate attestations given `attestation_data_root` + `slot` + `committee_index`.
Part of #445
=> Add getAggregatedAttestationV2 to support EIP-7549

types/primitive.yaml
The blobs returned from the beacon-apis are the raw bytes not encoded into ssz. 
Mentioning it as SSZ encoded cause confusion to decode the output from the API e.g. `ssz.Blob.decode(api_response)` which will not match with the actual blobs. 
Some reference: 
https://github.com/ChainSafe/lodestar/blob/ae984f0f6079f78c2445f36ae2ac09c9e868197e/packages/types/src/deneb/types.ts#L8
=> Fix the blob encoding type

.github/workflows/deploy.yaml, .github/workflows/main.yml, .github/workflows/release.yaml, .github/workflows/spellcheck.yml
Update github actions / workflows to use latest versions and swaps out deprecated actions with maintained ones. This also simplifies a few upload / bundling steps.
I have tested all workflows on a forked repo, everything seems to work as before.
=> Update CI tooling to latest versions

.github/workflows/pre-release.yaml, .github/workflows/release.yaml, README.md, wordlist.txt
**Motivation**
This is a proposal for pre-releases of the beacon api spec similar to what's done on the consensus spec. This allows clients to run spec tests earlier in the development cycle.
**Description**
A pre-release can be created by simply pushing a new tag with the suffix `-alpha.x`. The CD will create a github release and upload the bundled spec files.
Pre-releases will not be listed in `index.html` and not show up on the explorer.
=> Add workflow to create pre-releases

.github/changes-template.md, .github/workflows/pre-release.yaml, .github/workflows/release.yaml, CHANGES.md, README.md
This PR removes [manual steps](https://github.com/ethereum/beacon-APIs?tab=readme-ov-file#releasing) required to create a new release.
All steps are now handled by the CI after pushing a tag, this includes
- update spec version `info.version` in `beacon-node-oapi.yaml`
- add new entry to `index.html` in the format `{url: "./releases/<tag>/beacon-node-oapi.json", name: "<tag>"},`
- update changelog file (`CHANGES.md`) by moving entries to `## <tag>` section
- create github release and upload bundled spec files
- create release notes from changelog entries
=> Fully automate release process

apis/beacon/blocks/blinded_blocks.yaml, apis/beacon/blocks/blocks.yaml
v2 versions of [/eth/v1/beacon/blocks](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/publishBlock) and [/eth/v1/beacon/blinded_blocks](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/publishBlindedBlock) were added during Deneb, therefore we can deprecate v1 versions in Electra and remove them in the F-fork.
=> Deprecate v1 block publishing

apis/beacon/light_client/bootstrap.yaml, apis/beacon/light_client/finality_update.yaml, apis/beacon/light_client/optimistic_update.yaml, apis/beacon/light_client/updates.yaml, beacon-node-oapi.yaml, types/deneb/light_client.yaml, types/electra/light_client.yaml
- Add LC related types for Deneb and Electra
- Update exist LC endpoints to include Deneb and Electra types
Note this PR is drafted according to the consensus spec in ethereum/consensus-specs#3875. As such, `Electra/LightClientHeader` is missing intentionally since it will be identical to `Deneb/LightClientHeader` after the PR is merged.
=> Add Deneb and Electra light client spec

apis/beacon/blocks/attestations.v2.yaml, apis/beacon/blocks/blinded_blocks.v2.yaml, apis/beacon/blocks/blinded_blocks.yaml, apis/beacon/blocks/blocks.v2.yaml, apis/beacon/blocks/blocks.yaml, apis/beacon/pool/attestations.v2.yaml, apis/beacon/pool/attester_slashings.v2.yaml, apis/validator/aggregate_and_proofs.v2.yaml, beacon-node-oapi.yaml
The `Eth-Consensus-Version` header usage is ambiguous and could be misinterpreted. It shouldn't be tied up to the data schema but rather to the consensus version/fork the data belongs to.
For example since EIP7549, there are 2 possible attestations schemas only: `Attestation` (phase0) and `Electra.Attestation` (electra) but that doesn't mean that the `Eth-Consensus-Version` can only be `phase0` or `electra` but rather any value according to when the attestation is submitted or retrieved (Example: a `deneb` attestation will have an `Attestation` schema and `deneb` as value in the `Eth-Consensus-Version`).
When it come to the block related APIs, the problem is less concerning because there is schema per fork and hence any value could be used.
=> clarify the consensus version headers

types/electra/block.yaml
Latest changes from https://github.com/ethereum/builder-specs/pull/101 pass `execution_requests` instead of just the root in the blinded block, see PR for rationale.
=> Update blinded block to contain execution requests instead of root

types/electra/deposit.yaml, types/electra/state.yaml
The latest spec renames `PendingBalanceDeposit` to `PendingDeposit`. Same with the field `pending_balance_deposits` to `pending_deposits` in beacon state
=> Rename `PendingBalanceDeposit` to `PendingDeposit`

apis/debug/fork_choice.yaml
I don't think it makes sense for the response to omit `fork_choice_nodes`, it should be a required property.
Ref https://github.com/ethereum/beacon-APIs/pull/232
=> Make nodes required in debug fork choice endpoint

apis/beacon/rewards/blocks.yaml, beacon-node-oapi.yaml
- https://github.com/ethereum/pm/issues/973#issuecomment-1982438797
- https://gist.github.com/tersec/4d6326a915a2c215476c3ab5ac74b341
Implements the agreed-upon outcome of the discussion in that call.
=> disambiguate and ensure consistency of `proposeBlockV3`/`getBlockRewards` consensus block value

apis/beacon/pool/attestations.v2.yaml
The intend of https://github.com/ethereum/beacon-APIs/pull/492 was to apply `oneOf` to `submitPoolAttestationsV2` but it was applied to `getPoolAttestationsV2` which causes issues as outlined here https://github.com/ethereum/beacon-APIs/pull/492#discussion_r1937508072.
Alternative would just be to use `anyOf` everywhere
=> Apply oneOf to submit attestations api as intended

apis/eventstream/index.yaml
Added `committee_bits` and reordered fields to match [Attestation](https://github.com/ethereum/consensus-specs/blob/a9e40ace97aa39ff9756bf88e27559d16697acb4/specs/electra/beacon-chain.md?plain=1#L350-L354) container from electra spec.
=> Update attestation event example for electra

.github/workflows/main.yml
Noticed CI build step was not triggered when the release workflow opened the PR here https://github.com/ethereum/beacon-APIs/pull/506 but we need that job to succeed to pass required merge checks.
This PR should solve this by running the job when the release commit is pushed to the branch.
=> Run CI build step if commit is pushed to release branch

apis/validator/register_validator.yaml
To accommodate https://github.com/ethereum/builder-specs/pull/110, since the endpoint is mostly just a pass through of the request from the validator client to the builder, this allows to skip an extra serialization step and overall should make it more seamless if SSZ is used.
=> Add SSZ support to register validator api

apis/validator/attestation_data.yaml
Currently, it's ambiguous whether a VC which specified a non-zero `committee_index` in Electra would get an `AttestationData` in return. This is a potential source of VC/BN Electra [interoperability issues](https://github.com/ethpandaops/ethereum-package?tab=readme-ov-file#beacon-node--validator-client-compatibility), as each VC or BN might rely on the other element of its pair for that client to enforce the 0-constraint. Ensure that the BN, at least, does so.
=> require that Electra produceAttestationData AttestationData have 0 committee_index

types/phase0/attestation_data.yaml
As noted by @tersec on [discord](https://discord.com/channels/595666850260713488/710831784991916072/1351216847642427522), the example(s) shown in [getAggregatedAttestationV2](https://ethereum.github.io/beacon-APIs/?urls.primaryName=v3.0.0#/Validator/getAggregatedAttestationV2) and other attestation related apis are not valid as post-electra the `index` in `AttestationData` must always be 0.
Eg. for `getAggregatedAttestationV2` it would show this example now
```json
{
"version": "electra",
"data": {
"aggregation_bits": "0x01",
"data": {
"slot": "1",
"index": "0",
"beacon_block_root": "0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2",
"source": {
"epoch": "1",
"root": "0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2"
},
"target": {
"epoch": "1",
"root": …
```
=> Update AttestationData example to use 0 as index to be valid post-electra

apis/beacon/states/validators.yaml
Similar https://github.com/ethereum/beacon-APIs/pull/453, clarifies handling of empty arrays, ie. if the value is `[]` then no filtering should be applied and all validators should be returned. Since this [caused interop issues](https://discord.com/channels/595666850260713488/892088344438255616/1348727918951665815) just recently, I think it's worth clarifying this behavior on the spec. 
cc @james-prysm @pawanjay176 are you fine with the described behavior?
=> Clarify handling of empty arrays for ids/statuses in validators api

apis/config/spec.yaml
To accommodate https://github.com/ethereum/consensus-specs/pull/4277 and clarify format we expect to be returned from `/eth/v1/config/spec` api.
=> Add blob schedule example to config/spec api

apis/config/spec.yaml
The response for the `BLOB_SCHEDULE` should be a JSON array and the provided example does not conform to valid JSON. Updating to use double quotes as opposed to single quotes.
=> Update example to use valid json.

apis/debug/data_column_sidecars.yaml, beacon-node-oapi.yaml, types/fulu/data_column_sidecar.yaml, types/primitive.yaml
Introduces support for data column sidecars as part of EIP-7594 (PeerDAS):
- Add /eth/v1/debug/beacon/data_column_sidecars/{block_id} endpoint
- Define DataColumnSidecar and related types for Fulu fork
- Add Cell primitive type for 2048-byte data columns
=> Add data column sidecars debug endpoint

apis/beacon/states/pending_consolidations.yaml, apis/beacon/states/pending_deposits.yaml, apis/beacon/states/pending_partial_withdrawals.yaml
As suggested in https://github.com/ethereum/beacon-APIs/pull/539#discussion_r2139507320
=> Replace 415 response with 406 for apis that only have ssz response body

apis/validator/attestation_data.yaml
In electra, we are not required to call the endpoint for validators in different committees for the same slot.
The committeeIndex parameter is essentially redundant and could be always set to 0.
=> attestation_data api clarification for Electra

types/primitive.yaml
Noticed versioned hash example added in https://github.com/ethereum/beacon-APIs/pull/546 does not have correct length.
=> Update versioned hash example
